### PR TITLE
add packages necessary for smdm course

### PR DESCRIPTION
**Pull request by ShimantoRahman**

### CODE REVIEW

**Comment by bmesuere** [comment]
I'm not an export in R, but there seems to be overlap in at least the tidyverse package. ggplot2 and dplyr were already included as separated packages. I don't know if this might cause version conflicts?

**Comment by ShimantoRahman** [comment]
You correct that both ggplot2 and dplyr are already included in the tidyverse package. I have not used the R judge with these packages yet so i'm unsure if this would cause conflicts. However this commit does not add tidyverse to this list (it was already included). The only packages added are ISLR and MASS. The commit only shows a new line for tidyverse since I added "&& \" at the end of the line.

**Review by bmesuere — APPROVED** [review]

**Comment by bmesuere** [comment]
@rien do we still need a manual pull on the workers when these are built?

**Comment by rien** [comment]
Yes, this was needed the last time we needed a new iamge.

**Pull request merged**
