### PR TITLE
Add Dockerfile for Nextflow judge

### PR DESCRIPTION
**Pull request by Bond-009**
This Dockerfile contains all dependencies for a Nextflow judge.
Also included are FasQC, MultiQC and Trimmomatic as these bioinformatics tools are often used in Nextflow scripts.

### CODE REVIEW

**Comment by Bond-009** [comment]
Would the Dodona team be willing to take over stewardship of this judge too?
https://github.com/Bond-009/judge-nextflow

**Review by jorg-vr — CHANGES_REQUESTED** [review]
We have recently stareted to use HEREDOC in our newe docker files. See https://github.com/dodona-edu/docker-images/blob/master/dodona-tested.dockerfile

This way the `RUN` command becomes a lot more readable and it allows for comments explaining what's happening. Which hopefully improves maintainability in the future.

Would you be willing to update this docker file to use HEREDOC?

**Comment by jorg-vr** [comment]
> e Dodona team be willing to take over stewardship of this judge too?
> https://github.com/Bond-009/judge-nextflow

Yes, we would be willing to do so. Thanks for this addition to the project!
Could you transfer this judge to dodona-edu? Or make me co-owner so I can do the transfer?

**Comment by Bond-009** [comment]
> We have recently stareted to use HEREDOC in our newe docker files. See [`master`/dodona-tested.dockerfile](https://github.com/dodona-edu/docker-images/blob/master/dodona-tested.dockerfile)
> 
> This way the `RUN` command becomes a lot more readable and it allows for comments explaining what's happening. Which hopefully improves maintainability in the future.
> 
> Would you be willing to update this docker file to use HEREDOC?

Maybe I'm missing something, but you can already add comments without using HEREDOC? (just not completely empty lines)
Also it seems like using HEREDOC silently drops errors? (Which is to be expected if it's behaving like a shell script)

For example these 2 Dockerfiles. The first one fails to build (as expected) while the one using HEREDOC only cares about the exit status of the last command.
```docker
FROM alpine:3.21

RUN commandthatdoesntexist && \
	echo test
```

```docker
FROM alpine:3.21

RUN <<EOF
commandthatdoesntexist
echo test
EOF
```

This issue is solvable by using `set -e` at the top of the "file"
I can change this PR to use HEREDOC in combination with `set -e` if that's preferred.

**Comment by jorg-vr** [comment]
Thanks for the extra info! I didn't know about the silent dropping of errors.

I would prefer HEREDOC indeed, with `set -e` as suggested by you :)

And yes, comments can already be added, but in my experience readability is greatly improved, compared to 10 or more lines with `&& \`

**Comment by jorg-vr** [comment]
And thanks for adding me to the repo, but I'll need more permissions to transfer it to our organisation: see https://stackoverflow.com/a/34982788

**Comment by Bond-009** [comment]
> And thanks for adding me to the repo, but I'll need more permissions to transfer it to our organisation: see [stackoverflow.com/a/34982788](https://stackoverflow.com/a/34982788)

This just says how to transfer a repo, not how to give the permission to do so.
Since I'm unable to transfer to dodona-edu as I don't have repo creation permissions I requested a transfer to your account and you can transfer it to the org. I hope that works.
If only GitHub had a better permission system or transfer requests to orgs...

**Comment by jorg-vr** [comment]
It worked. The repo can now be found here: https://github.com/dodona-edu/judge-nextflow

Remind me to add the judge in dodona, once this docker pr is merged.

**Review by jorg-vr — APPROVED** [review]

**Comment by Bond-009** [comment]
@jorg-vr Thanks, that sounds good to me.

**Comment by Bond-009** [comment]
@jorg-vr Thank you! The Docker judge seems to be working as expected now.

**Pull request merged**
