### PR TITLE
Don't run the main.sh as root

### LINKED ISSUE #5: The use of bash in main.sh and logger.sh
The R docker image I'm preparing, is based on alpine linux and doesn't come with a bash shell (alpine uses the ash shell). 

Can `#!/bin/bash` be replaced with `#!/bin/sh` in main.sh and logger.sh? If not, I'll install the bash shell in the docker image (but I like to keep it as minimal as possible).

_[Original issue](https://github.ugent.be/dodona/docker-images/issues/5) by jfmeys on Thu Apr 05 2018 at 17:55._

### PR DESCRIPTION
**Pull request by ninewise**
- Closes #5
- Closes #6
- Closes #20
- Closes #21

### CODE REVIEW

**Comment by ninewise** [comment]
- [x] dodona-anaconda3 ([test submission](https://naos.ugent.be/nl/submissions/980252/))
- [x] dodona-bash ([test submission](https://naos.ugent.be/nl/submissions/980255/))
- [x] dodona-biopythia ([test submission](https://naos.ugent.be/nl/submissions/980253/))
- [ ] dodona-csharp (none): untested, I have no exercises on Naos
- [x] dodona-haskell ([test submission](https://naos.ugent.be/nl/submissions/980250/))
- [x] dodona-java ([test submission](https://naos.ugent.be/nl/submissions/980254/))
- [x] dodona-nodejs ([test submission](https://naos.ugent.be/nl/submissions/980246/))
- [x] dodona-prolog ([test submission](https://naos.ugent.be/nl/submissions/980247/))
- [x] dodona-r ([test submission](https://naos.ugent.be/nl/submissions/980248/))
- [ ] dodona-scratch ([test submission](https://naos.ugent.be/nl/submissions/980256/)): Internal Error, no idea why.

**Comment by bmesuere** [comment]
@ninewise create a `main-legacy.sh` for csharp and scratch?

**Comment by bmesuere** [comment]
@nnmak Do you have any idea what goes wrong?

**Comment by ninewise** [comment]
The scratch-judge doesn't work with the docker image build from the dockerfile before these changes, either. The original docker images on Naos (tagged dodona-scratch-old now) does work, but I've no idea which dockerfile it was build from.

Dieter will test the C-sharp judge soon. I'd wait for this and merge the PR when he confirms it works.

**Comment by dmouriss** [comment]
@ninewise 

The c-sharp judge works with the updated main script.

**Comment by ninewise** [comment]
Then I'd merge this. The scratch-judge isn't actively used and can be fixed later.

**Pull request merged**
